[package]
name = "wifi-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
env_logger = "0.11.9"
gtk4 = { version = "0.10.3", features = ["v4_12"] }
gtk4-layer-shell = "0.7.1"
log = "0.4.29"
zbus = "5.13.2"
